### ISSUE TITLE
Meeting point

### ISSUE THREAD

**Issue by gortazar** [gsalguero/jenkins-performance-plugin#1]
Este issue es para comprobar que nos vemos. Contesta para saber que tienes acceso.

**Comment by gsalguero** [comment]
Te respondo atraves de Zube.io, veo el proyecto sin problemas.

**Comment by gortazar** [comment]
Ok. Algunas cuestiones primero:
- ¿Estás familiarizado con git?
- ¿Entiendes o intuyes cómo funciona zube.io desde el punto de vista de la planificación del proyecto?

**Comment by gsalguero** [comment]
Te respondo:
- ¿Estás familiarizado con git? **No, es la primera vez que lo uso.**
- ¿Entiendes o intuyes cómo funciona zube.io desde el punto de vista de la planificación del proyecto? **Por lo que he visto, supongo que lo gestionaremos como un proyecto Scrum. Aunque la creación de tarjetas de tareas no se quien de los dos la gestionara.**

**Comment by gortazar** [comment]
Jeje, veo que la parte del gestión del proyecto la conoces. 
Por la parte de git no te preocupes, os mandaré algunos recursos para que os pongáis al día.
En los próximos días daré de alta algunos issues para que te vayas poniendo poco a poco con el proyecto.
